### ISSUE TITLE
Error playing a video (0xC0000005)

### ISSUE THREAD

**Issue by felipe9962** [caprica/vlcj-javafx-demo#30]
Hi! I'm writing to you because I'm doing a class Javafx project and I'm trying to do a kind of VLC/Netflix. My problem is that when I start playing the video, it looks good and the audio plays without any problem but I get this:

Process finished with exit code -1073741819 (0xC0000005)

Do you know what it could be?
Thanks a lot!

**Comment by caprica** [comment]
The most likely reason is you are not keeping your Java objects alive and they are being garbage collected.

Maybe check this http://capricasoftware.co.uk/projects/vlcj-4/tutorials/garbage-collection

Otherwise you will need to post a minimal code example that demonstrates your problem, otherwise it's impossible to help you with the little information you provided.

You could also check your own code against what the javafx-demo code does, I will be very surprised if the javax-demo code quits with that error code you posted.

**Comment by felipe9962** [comment]
Thank you very much! It turns out that I was the garbage collector, I'm not very familiar with it, but I've learned something new from it. 
I was creating the object within the method and not as an attribute.
By the way, you did a great job! I'll follow your updates if you keep at it.

**Comment by caprica** [comment]
The thing is most Java developers don't often get exposed to the garbage collector, and usually that's fine.

What I mean is, the effects are not noticeable.

But when a vlcj object gets garbage collected, it has hooks into native code. The Java object is gone, but the native code is still running. When the native code tries to call back into the Java (which no longer exists) it has nowhere to go so it crashes.

It's a common issue, but it is documented in the tutorial and the project README.
