### ISSUE TITLE
Force an image render at current location in paused video

### ISSUE THREAD

**Issue by GeePawHill** [caprica/vlcj-javafx-demo#32]
Is there a way to force a rendering to the ImageView at a particular time with a given position? My application allows editing of a graphics layer by positioning the video and taking various commands. The problem is that I can't find a way to force the Image to update at an arbitrary position when the video is paused.

A simple illustration of the desired functionality: run any of the animation modes in vlcj-javafx-demo. Open a video and pause it. Drag the position bar. 

What will happen: nothing, until the video is resumed, when the image is then updated. 
What I want to happen: when the drag is ended, the image is updated to reflect the new position.

I tried a couple of hacks: issuing a play/pause pair, or expressly calling the pixelbuffer update. The former works but intermittently. The latter does not. 

It occurs to me that the play/pause intermittency might be that I need some way to latch that I'm waiting for a new call to the pixelbuffer update before I issue the pause. But I thought I would ask before I fool around with that, as maybe there's something simple I'm just not getting.

Thanks!
GeePaw

**Comment by caprica** [comment]
I wrote a reply to this that has somehow been mislaid, so here goes again...

Presumably you are using VLC 3.x. Seeking didn't have the best implementation in VLC 3.x and results in the issues you've described here.

Seeking is MUCH improved in VLC 4.x. I just now tested the vlcj-5.0.0 branch of vlcj and this JavaFX application using VLC 4 and seeking while paused works properly (including the sending of events while paused).

The problem is that VLC 4.0.0 is likely still some considerable way from being finished development, so unless you want to try some bleeding-edge builds switching to VLC 4.x may not be feasible for you right now, but that IS the right answer.

There's nothing that can be done from the Java side to fix this, the problem is on the native side.

**Comment by GeePawHill** [comment]
Thanks for the speedy answer! It's at least good to know that I'm not using it incorrectly. I'm not on any desperate deadline, so I will wait for VLC4 to stabilize and make the switchover then.

**Comment by caprica** [comment]
The VLC 4 git master branch is stable for me, I sync with it and build it myself quite often. That's on Linux.

If you're on Windows you could try and download a nightly build but it has some risk in doing so I suppose. It would also mean you would need to change to vlcj-5.0.0-SNAPSHOT, which you'd have to build yourself. It's all a bit messy right now with pre-release versions of things.

VLC 4 seems to have a lot of improvements so I hope it's released soon - but honestly I have no clue when, it can go *years* between major VLC releases.
