### ISSUE TITLE
Video playback issues with some HD videos

### ISSUE THREAD

**Issue by rdkgit** [caprica/vlcj-javafx-demo#54]
Hi!

Testing on windows and linux with several different HD videos.  Many play just fine.  For a few, I get a lot of playback errors.
Video is a MP4  Base Media v1 [IS0 14496-12:2003]
VLC from command-line plays the video just fine.
Error is: [hevc @ 0x7f0d20309b40] Could not find ref with POC 14
JavaFX 22.0.2
Java 19
VLCJ 4.7.0
I've borrowed this code and am running it in my own test app as I can't get this repo to build and run.  Separate issue.
I see the comments/suggestions about PixelBuffer but don't see that in this code base. 
Any suggestions as to what to try next?

**Comment by rdkgit** [comment]
I'm using the ImageViewVideoSurface widget with an ImageView.

**Comment by rdkgit** [comment]
Perhaps this issue should be filed under caprica/vlcj-javafx repo?

**Comment by caprica** [comment]
Well, the thing is, vlcj isn't really doing anything here other than joining all the parts together. So if it works for some videos but not others, then this is probably something going on in VLC's render callbacks.

When comparing with VLC itself, it is not really an apples-to-apples comparison, because VLC is NOT using the same rendering/video-output path - IIRC JavaFX is using the imem renderer that is exposed by LibVLC, but VLC itself will be using something more optimal, like an OpenGL or D3D rendering path.

So to do a comparison like this, you would need to setup VLC to use the imem filter (and this is not straightforward from the command line).

**Comment by caprica** [comment]
As you have mentioned, PixelBuffer is the recommended approach generally but even so I don't think that will help with this issue.

**Comment by rdkgit** [comment]
Thanks for your clarification.  What is also interesting is that the JavaFX media player can play a different subset of my 3 test videos. 

Also, re pixelbuffer, tracing through the code, it looks like the ImageView and video surface settings are using the PixelBuffer.  

So, I'm not sure how to proceed.

**Comment by caprica** [comment]
Well, this error comes from VLC:

>Error is: [hevc @ 0x7f0d20309b40] Could not find ref with POC 14

I have no idea what that means.

Sometimes I suppose you can get errors if the playback rate can not keep up because of insufficient or over-burdened resources. The rendering that vlcj-javafx uses is more CPU intensive than other approaches, but there is no alternative.

To get a baseline, you could try running your media files with a non-JavaFX vlcj media player, like `EmbeddedMediaPlayerComponent` or something. It would be interesting to see if with that approach you get the same errors or not.

But even so, that will not solve the issue.

**Comment by caprica** [comment]
And just to be more clear, the rendering path that vlcj-javafx uses is sub-optimal, but there is no real alternative (well, with vlcj 5.x you will be able to use an OpenGL rendering path instead, but that will necessitate writing your application as an OpenGL application). The VLC application uses the most optimal render path with appropriate hardware-accelerated decoding/rendering where possible.

**Comment by rdkgit** [comment]
Thank you.  I am using the EmbeddedMediaPlayer.  Here is rough outline of my setup code.

```
        factory = new MediaPlayerFactory();
        mediaPlayer = factory.mediaPlayers().newEmbeddedMediaPlayer();
        videoImageView = new ImageView();
        r = new ResizableImageView(videoImageView);
        videoImageView.setPreserveRatio(true);
        videoImageView.setPreserveRatio(true);
        videoImageView.fitWidthProperty().bind(borderPane.widthProperty());
        videoImageView.fitHeightProperty().bind(borderPane.heightProperty().subtract(150));
        mediaPlayer.videoSurface().set(new ImageViewVideoSurface(videoImageView));
        mediaPlayer.media().prepare(videoFile.toString());
```

Did I do something dumb in setup?

Thanks.

**Comment by caprica** [comment]
I mean to try an EmbeddedMediaPlayer with an "ordinary" video surface, for comparison.  So basically I mean a normal Swing application, not a JavaFX one.

**Comment by rdkgit** [comment]
Thanks!  My code is all JavaFX.  Can you point me to an example to borrow from for ordinary video surface?

**Comment by caprica** [comment]
https://github.com/caprica/vlcj/blob/vlcj-4.x/src/test/java/uk/co/caprica/vlcj/test/minimal/MinimalTestPlayer.java

**Comment by rdkgit** [comment]
Thank you!  Last dumb question of the day/evening.  I'm struggling to build and run these demo programs.  
I've tried various invocations of maven but no luck.
mvn dependency:resolve worked to download dependencies.
But not sure what other mvn commands to run.  I'm sure its obvious but I'm new to maven and projects structured for it.
Thanks,
Bobby

**Comment by caprica** [comment]
I can't give you that level of support, sorry. I can only suggest you use an IDE like IntelliJ IDEA (Community Edition is free) and it's mostly very easy from there on.

**Comment by rdkgit** [comment]
Hi!
Ahh, thats all I needed to hear.  I'm an emacs person . . . :)  I'll give an IDE a whirl.  Thank you.

**Comment by rdkgit** [comment]
Hi!
Thank you for the info.  I downloaded intellij and was able to build the MinimalTestPlayer and it played all three of my test videos.  SO, that means its javafx and the surface setting.  I still need to use javafx due to the rest of my app but I'll see about trying to use a swing surface.  Thank you.

**Comment by caprica** [comment]
Hmm. So, as I said earlier, the JavaFX rendering path for video is different, using IIRC the "imem" filter/plugin in VLC.

I'm really not sure what can be done here, certainly it seems the problem is not in vlcj itself.

Mixing Swing and JavaFX is very painful tbh, with no optimal way to do it. If you try and put a Swing component for the video inside a JavaFX scene, it will NOT render correctly.

The only think you can really do is put it in a separate Frame/Window and keep it in sync with size and position when the scene changes. This is similar to the heavyweight overlay solution. It's laggy when resizing and moving windows though.

**Comment by rdkgit** [comment]
Ugh.  Thank you.  For what its worth, I also tried JavaFX 23 and Java 21.  Still no luck.  I found somewhere on interwebs to mix a java awt/swing component in javafx.  I'm used to writing ugly code :)

**Comment by caprica** [comment]
But that's what I'm saying, even if you can insert an AWT/Swing component into the scene, the video will not render correctly.

With JavaFX you basically must use a software-rendered approach.
